### PR TITLE
Optimized Chinese translation

### PR DESCRIPTION
**Pull request by SchumyHao**
Signed-off-by: SchumyHao <schumyhaojl@126.com>

### CODE REVIEW

**Comment by SchumyHao** [comment]
Words in www folder is no needed?

**Comment by ldittmar81** [comment]
Of corse they are needed. Create it with gulp wwwLanguages2words

**Comment by sbormann** [comment]
@SchumyHao  Thanks for your translations!! I deleted words.js because i added a few translations as well and re-created the words.js by using gulp.  Please check if everything has worked out, i think it should work now. Greeings, Sebastian

**Comment by SchumyHao** [comment]
> @SchumyHao Thanks for your translations!! I deleted words.js because i added a few translations as well and re-created the words.js by using gulp. Please check if everything has worked out, i think it should work now. Greeings, Sebastian

OK，
It's fine if you generate new words.js from /www/i18n/ folder.
Because I update /www/i18n/zh-cn/translation.json too.

**Comment by SchumyHao** [comment]
But it still missing for now

**Pull request merged**
